# Generated by Django 2.2.3 on 2020-07-17 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Имя на русском')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Имя на английском')),
                ('title_jp', models.CharField(blank=True, max_length=200, verbose_name='Имя на японском')),
                ('image', models.ImageField(blank=True, upload_to='pokemons', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('next_evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nxt_evolution', to='pokemon_entities.Pokemon', verbose_name='В кого эволюционирует')),
                ('previous_evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prv_evolution', to='pokemon_entities.Pokemon', verbose_name='Из кого эволюционирует')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Координата широты')),
                ('lon', models.FloatField(verbose_name='Координата долготы')),
                ('appeared_at', models.DateTimeField(verbose_name='Дата и время появления')),
                ('disappeared_at', models.DateTimeField(verbose_name='Дата и время исчезновения')),
                ('level', models.IntegerField(verbose_name='Уровень')),
                ('health', models.IntegerField(blank=True, null=True, verbose_name='Здоровье')),
                ('strength', models.IntegerField(blank=True, null=True, verbose_name='Атака')),
                ('defence', models.IntegerField(blank=True, null=True, verbose_name='Защита')),
                ('stamina', models.IntegerField(blank=True, null=True, verbose_name='Выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.Pokemon')),
            ],
        ),
    ]
